// Generated by tools/seeds/synchronize-demo-image-pools.mjs.
// Frontend-local keeps remote placeholders; the standalone HTTP demo uses the same logical slots from MinIO.
export interface DemoAssetPlaceholder {
  slot: number;
  imageUrl: string;
  title: string;
  subtitle: string;
  details: string;
  category: string;
}

type DemoAssetDefinition = Omit<DemoAssetPlaceholder, 'slot' | 'imageUrl'>;

const ASSET_PICSUM_IDS = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49] as const;
const EVENT_PICSUM_IDS = [50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,87,88,89,90,91,92,93,94,95,96,98,99,100,101,102,103,104,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,139,140,141,142,143,144,145,146,147,149,151,152,153,154,155] as const;

const PUBLIC_LOCAL_USER_IDS = ["u1","u2","u3","u4","u6","u7","u8","u10","u12","u13","u14","u15","u16","u18","u19","u20","u22","u24","u25","u26","u27","u28","u30","u31","u32","u34","u36","u37","u38","u39","u40","u42","u43","u44","u46","u48"] as const;

const ASSET_SLOTS_BY_TEMPLATE: Readonly<Record<string, readonly number[]>> = {
  "asset-sup-1": [
    1,
    2,
    3,
    4
  ],
  "asset-sup-2": [
    9,
    10,
    11,
    12
  ],
  "asset-sup-3": [
    13,
    14,
    15,
    16
  ],
  "asset-sup-4": [
    5,
    6,
    7,
    8
  ],
  "asset-sup-5": [
    1,
    2,
    3,
    4
  ],
  "asset-sup-6": [
    13,
    14,
    15,
    16
  ],
  "asset-sup-7": [
    5,
    6,
    7,
    8
  ],
  "asset-sup-8": [
    13,
    14,
    15,
    16
  ],
  "asset-acc-1": [
    17,
    18,
    19,
    20
  ],
  "asset-acc-2": [
    25,
    26,
    27,
    28
  ],
  "asset-acc-3": [
    21,
    22,
    23,
    24
  ],
  "asset-acc-4": [
    29,
    30,
    31,
    32
  ],
  "asset-transport-1": [
    33,
    34,
    35,
    36
  ],
  "asset-transport-2": [
    37,
    38,
    39,
    46,
    47
  ],
  "asset-transport-3": [
    40,
    41,
    42,
    43,
    44,
    45
  ],
  "asset-transport-4": [
    48,
    49,
    50
  ]
};

const ASSET_DEFINITION_BY_SLOT: Readonly<Record<number, DemoAssetDefinition>> = {
  "1": {
    "title": "Lakeside Basecamp Bundle",
    "subtitle": "4-person dome + sleep systems + lantern",
    "details": "Packed for a two-night lakeside stay; cookware and lighting are included.",
    "category": "Camping"
  },
  "2": {
    "title": "Desert Trail Hydration Set",
    "subtitle": "Water carriers + sun protection + trekking poles",
    "details": "Heat-ready hiking supplies for a dry exposed route and a managed rest checkpoint.",
    "category": "Hiking"
  },
  "3": {
    "title": "Coastal Kayak Safety Set",
    "subtitle": "PFDs + paddles + dry bags + tow line",
    "details": "Launch-ready water-safety equipment for a small sea-kayak group.",
    "category": "Watersports"
  },
  "4": {
    "title": "Winter Mountaineering Safety Set",
    "subtitle": "Crampons + ice axes + rope + helmets",
    "details": "Cold-weather technical equipment organized for a supervised alpine route.",
    "category": "Mountaineering"
  },
  "5": {
    "title": "Mobile Group Catering Station",
    "subtitle": "Coolers + prep tables + food crates",
    "details": "Group meal station packed for hygienic outdoor preparation and cold storage.",
    "category": "Catering"
  },
  "6": {
    "title": "Group Safety Base",
    "subtitle": "First aid + radios + hi-vis equipment",
    "details": "Central safety point for moving groups, night checks, and incident response.",
    "category": "Safety"
  },
  "7": {
    "title": "Trailside Bicycle Repair Kit",
    "subtitle": "Pumps + patches + spare tubes + tools",
    "details": "Mobile maintenance supplies for punctures and basic repairs during a group ride.",
    "category": "Cycling"
  },
  "8": {
    "title": "Outdoor Event Power Hub",
    "subtitle": "Power stations + charging leads + cable covers",
    "details": "Shared low-voltage charging and equipment-power point for an outdoor gathering.",
    "category": "Event Technology"
  },
  "9": {
    "title": "Travel Social Games Case",
    "subtitle": "Compact boards + cards + dice + score tokens",
    "details": "Portable all-weather social games for four travelers during an evening stop.",
    "category": "Games"
  },
  "10": {
    "title": "Route Navigation Kit",
    "subtitle": "Handheld GPS + compass + waterproof map sleeves",
    "details": "Offline route-finding equipment for a small group traveling beyond reliable mobile coverage.",
    "category": "Navigation"
  },
  "11": {
    "title": "Field Cooking Kit",
    "subtitle": "Twin burner + nesting pots + utensil roll",
    "details": "Compact meal-preparation equipment for four people at an approved outdoor cooking point.",
    "category": "Cooking"
  },
  "12": {
    "title": "Picnic Comfort Set",
    "subtitle": "Folding chairs + blanket + thermos carriers",
    "details": "Packable seating and serving equipment for a relaxed daytime group stop.",
    "category": "Picnic"
  },
  "13": {
    "title": "Portable Audio Rig",
    "subtitle": "Battery speakers + microphones + compact mixer",
    "details": "Cable-managed sound equipment for announcements, music, or a small workshop.",
    "category": "Audio"
  },
  "14": {
    "title": "Rechargeable Area Lighting Kit",
    "subtitle": "Tripod lights + lanterns + safe cable covers",
    "details": "Flexible low-voltage lighting for an evening meeting point or work area.",
    "category": "Lighting"
  },
  "15": {
    "title": "Outdoor Projection Pack",
    "subtitle": "Projector + folding screen + power station",
    "details": "Portable film and presentation setup for a sheltered community gathering.",
    "category": "Projection"
  },
  "16": {
    "title": "Hygiene and Cleanup Station",
    "subtitle": "Water containers + wash basins + sorting bins",
    "details": "Reusable sanitation and cleanup equipment for a shared trip or outdoor event.",
    "category": "Sanitation"
  },
  "17": {
    "title": "Lakeside Timber Cabin",
    "subtitle": "Four beds + wood stove + covered porch",
    "details": "Simple group cabin for a quiet overnight stay beside a lake.",
    "category": "Cabin"
  },
  "18": {
    "title": "Urban Hostel Family Room",
    "subtitle": "Four bunks + lockers + shared table",
    "details": "Private four-person hostel room near public transport and city activities.",
    "category": "Hostel"
  },
  "19": {
    "title": "Riverside Houseboat Berth",
    "subtitle": "Two double berths + compact galley + deck",
    "details": "Moored floating accommodation for a small group on a calm urban river.",
    "category": "Houseboat"
  },
  "20": {
    "title": "Mountain Refuge Room",
    "subtitle": "Four alpine bunks + drying racks + gear shelf",
    "details": "Practical shared room inside a staffed mountain refuge.",
    "category": "Mountain Refuge"
  },
  "21": {
    "title": "Compact Campervan Sleep Setup",
    "subtitle": "Pop-top berths + convertible bench + kitchenette",
    "details": "Four-person mobile sleep setup prepared at a legal overnight stop.",
    "category": "Campervan"
  },
  "22": {
    "title": "Farm Guest Cottage",
    "subtitle": "Two bedrooms + kitchen table + rural courtyard",
    "details": "Independent small cottage for a group visiting a working farm.",
    "category": "Cottage"
  },
  "23": {
    "title": "Desert Adobe Casita",
    "subtitle": "Cool plaster walls + shaded courtyard + sleeps four",
    "details": "Compact heat-conscious guest house with enclosed sleeping rooms and a furnished courtyard.",
    "category": "Casita"
  },
  "24": {
    "title": "Forest Treehouse Lodge",
    "subtitle": "Raised timber room + four beds + woodland deck",
    "details": "Weatherproof elevated lodge reached by a safe fixed stairway.",
    "category": "Treehouse"
  },
  "25": {
    "title": "Historic Townhouse Room",
    "subtitle": "Double bed + reading nook + tall window",
    "details": "Private two-person room in a carefully maintained older city home.",
    "category": "Guest Room"
  },
  "26": {
    "title": "Beach Bungalow Room",
    "subtitle": "Double bed + screened shutters + small veranda",
    "details": "Simple two-person coastal stay designed for airflow and sandy gear.",
    "category": "Bungalow"
  },
  "27": {
    "title": "Accessible Garden Suite",
    "subtitle": "Wide circulation + low storage + roll-in bathroom",
    "details": "Step-free private suite for two guests beside a quiet garden.",
    "category": "Accessible Suite"
  },
  "28": {
    "title": "Urban Micro Studio",
    "subtitle": "Wall bed + kitchenette + compact workspace",
    "details": "Efficient self-contained city stay for one or two travelers.",
    "category": "Studio"
  },
  "29": {
    "title": "Festival Crew Bunk Nook",
    "subtitle": "Two bunks + personal shelves + durable linens",
    "details": "No-frills two-person sleep space for event or volunteer crew.",
    "category": "Bunkhouse"
  },
  "30": {
    "title": "Night Train Sleeper Cabin",
    "subtitle": "Two berths + fold-down table + corridor window",
    "details": "Reserved overnight rail compartment for two travelers.",
    "category": "Sleeper Cabin"
  },
  "31": {
    "title": "Canal View Guest Room",
    "subtitle": "Double bed + balcony door + waterside outlook",
    "details": "Bright private room for two guests beside a quiet canal district.",
    "category": "Guest Room"
  },
  "32": {
    "title": "Remote Work Guest Suite",
    "subtitle": "Double bed + proper desk + acoustic door",
    "details": "Calm two-person suite with a reliable place for focused work.",
    "category": "Guest Suite"
  },
  "33": {
    "title": "Trail Access 4x4",
    "subtitle": "4 seats + high clearance + washable cargo area",
    "details": "Unbranded four-wheel-drive vehicle for rough access roads and trail equipment.",
    "category": "4x4"
  },
  "34": {
    "title": "Kayak Roof-Rack Estate",
    "subtitle": "4 seats + twin kayak rack + wet-gear liner",
    "details": "Long-roof vehicle prepared for a four-person coastal paddling day.",
    "category": "Estate Car"
  },
  "35": {
    "title": "Family Road-Trip Minivan",
    "subtitle": "4 reserved seats + flexible storage + sliding doors",
    "details": "Comfortable unbranded minivan configured for a longer regional journey.",
    "category": "Minivan"
  },
  "36": {
    "title": "Bicycle Shuttle Crossover",
    "subtitle": "4 seats + rear rack + repair tray",
    "details": "Compact crossover carrying two bicycles and group riding equipment.",
    "category": "Crossover"
  },
  "37": {
    "title": "Compact Airport EV",
    "subtitle": "4 seats + electric hatchback + terminal pickup",
    "details": "Small battery-electric car for a coordinated airport transfer.",
    "category": "Electric Car"
  },
  "38": {
    "title": "Accessible Shuttle Van",
    "subtitle": "4 passenger places + ramp + securement points",
    "details": "Step-friendly van configured for an inclusive local transfer.",
    "category": "Accessible Van"
  },
  "39": {
    "title": "Hotel Courtesy Minibus",
    "subtitle": "4 reserved seats + high roof + hotel loop",
    "details": "Small courtesy bus assigned to a four-person late-arrival group.",
    "category": "Minibus"
  },
  "40": {
    "title": "Expo Equipment Cargo Van",
    "subtitle": "4 crew seats + enclosed load bay + tie-downs",
    "details": "Short-wheelbase van for people and protected event equipment.",
    "category": "Cargo Van"
  },
  "41": {
    "title": "Community Equipment Pickup",
    "subtitle": "4 seats + covered utility bed + loading step",
    "details": "Double-cab pickup for bulky community-event supplies.",
    "category": "Pickup Truck"
  },
  "42": {
    "title": "Festival Utility Buggy",
    "subtitle": "4 seats + open cargo deck + venue route",
    "details": "Low-speed electric utility vehicle for an enclosed event site.",
    "category": "Utility Vehicle"
  },
  "43": {
    "title": "Waterfront Passenger Launch",
    "subtitle": "4 passenger seats + rigid cockpit + life jackets",
    "details": "Small licensed motor launch with an enclosed helm for a short sheltered-water transfer.",
    "category": "Passenger Boat"
  },
  "44": {
    "title": "Dinner District Electric Taxi",
    "subtitle": "4 seats + compact EV + city pickup",
    "details": "Quiet unbranded electric taxi reserved for an evening group.",
    "category": "Electric Taxi"
  },
  "45": {
    "title": "Concert Night Shuttle Van",
    "subtitle": "4 reserved seats + illuminated pickup zone",
    "details": "Compact passenger van for a clearly coordinated post-event return.",
    "category": "Shuttle Van"
  },
  "46": {
    "title": "Station Pickup Wagon",
    "subtitle": "4 seats + long cargo floor + rail connection",
    "details": "Unbranded estate wagon for a daytime station pickup.",
    "category": "Estate Car"
  },
  "47": {
    "title": "Historic District Pedicab Pair",
    "subtitle": "4 total seats + two open-air cycle taxis",
    "details": "Two coordinated roofless pedal-powered taxis for a short old-town transfer.",
    "category": "Pedicab"
  },
  "48": {
    "title": "Mountain Cable-Car Cabin",
    "subtitle": "4 reserved places + enclosed gondola + ridge link",
    "details": "Small enclosed cable-car cabin representing an uphill group transfer.",
    "category": "Cable Car"
  },
  "49": {
    "title": "Foothill Sidecar Motorcycle Pair",
    "subtitle": "4 total seats + two touring sidecars",
    "details": "Two coordinated unbranded sidecar motorcycles for a scenic paved route.",
    "category": "Motorcycle"
  },
  "50": {
    "title": "Snow Lodge Tracked Shuttle",
    "subtitle": "4 passenger seats + rubber tracks + heated cab",
    "details": "Compact tracked passenger vehicle for a maintained snowy lodge route.",
    "category": "Snow Shuttle"
  }
};

const EVENT_SLOT_BY_SEED: Readonly<Record<string, number>> = {
  "demo-event-events:u1:e1:alpine-weekend-2.0": 2,
  "demo-event-events:u1:e10:golden-hour-meetup": 94,
  "demo-event-events:u1:e11:cross-month-community-relay": 12,
  "demo-event-events:u1:e12:spring-cohort-journey": 68,
  "demo-event-events:u1:e7:coffee-+-book-swap": 39,
  "demo-event-events:u1:e9:brunch-rotation": 31,
  "demo-event-events:u10:e2:urban-photo-marathon": 52,
  "demo-event-events:u12:e8:lakeside-walk-lab": 15,
  "demo-event-events:u2:checkout-paid-slots:checkout-demo-·-paid-multi-slot": 73,
  "demo-event-events:u2:e13:afterwork-tasting-circle": 38,
  "demo-event-events:u2:e4:sunrise-run-+-brunch": 7,
  "demo-event-events:u2:waitlist-full-policy:full-house-supper-club": 36,
  "demo-event-events:u3:active-tournament-slots:tournament-demo-·-active-slot-cup": 3,
  "demo-event-events:u3:asset-join-demo-nagy-eszter:asset-join-demo-·-shuttle-seat": 69,
  "demo-event-events:u3:checkout-free-slots:checkout-demo-·-free-multi-slot": 74,
  "demo-event-events:u3:checkout-paid-policy:checkout-demo-·-paid-one-slot-policy": 75,
  "demo-event-events:u3:e14:moonlight-boardwalk-mixer": 17,
  "demo-event-events:u3:e3:night-food-league": 11,
  "demo-event-events:u3:e5:creative-studio-meetup": 46,
  "demo-event-events:u3:feedback-showcase-nagy-eszter-social:feedback-demo-·-social-lab": 76,
  "demo-event-events:u3:feedback-showcase-nagy-eszter-studio:feedback-demo-·-studio-recap": 51,
  "demo-event-events:u3:waitlist-full-free:tiny-vinyl-listening-room": 41,
  "demo-event-events:u4:e6:sunset-beach-volley": 4,
  "demo-event-hosting:u1:h1:weekly-padel-league": 5,
  "demo-event-hosting:u1:h2:spring-city-festival-crew": 45,
  "demo-event-hosting:u2:h3:sunday-bike-social": 6,
  "demo-event-hosting:u3:h4:creative-nights-series": 98,
  "demo-event-invitations:u1:i1:jazz-rooftop-session": 43,
  "demo-event-invitations:u1:i2:open-padel-pairs": 13,
  "demo-event-invitations:u1:i3:chat:-last-minute-ski-transfer": 1,
  "demo-event-invitations:u2:i4:foodie-crawl-team": 37,
  "demo-event-invitations:u3:i5:urban-photo-sprint": 9
};

export function demoAssetPlaceholder(seed: string): DemoAssetPlaceholder {
  const slot = demoAssetSlot(seed);
  const definition = ASSET_DEFINITION_BY_SLOT[slot] ?? ASSET_DEFINITION_BY_SLOT[1];
  return {
    ...definition,
    slot,
    imageUrl: `https://picsum.photos/id/${ASSET_PICSUM_IDS[slot - 1]}/1200/700`
  };
}

export function demoAssetPlaceholderUrl(seed: string): string {
  return demoAssetPlaceholder(seed).imageUrl;
}

function demoAssetSlot(seed: string): number {
  const normalized = seed.trim().toLowerCase();
  const template = Object.keys(ASSET_SLOTS_BY_TEMPLATE).find(key => normalized.includes(key));
  const candidates = template ? ASSET_SLOTS_BY_TEMPLATE[template] : [1];
  const ownerId = normalized.match(/(u\d+)-asset-/)?.[1] ?? '';
  const publicOwnerIndex = PUBLIC_LOCAL_USER_IDS.indexOf(ownerId as typeof PUBLIC_LOCAL_USER_IDS[number]);
  const candidateIndex = publicOwnerIndex >= 0
    ? publicOwnerIndex % candidates.length
    : stableIndex(normalized, candidates.length);
  return candidates[candidateIndex] ?? 1;
}

export function demoEventPlaceholderUrl(seed: string): string {
  const normalized = seed.trim().toLowerCase();
  const slot = EVENT_SLOT_BY_SEED[normalized] ?? (stableIndex(normalized, EVENT_PICSUM_IDS.length) + 1);
  return `https://picsum.photos/id/${EVENT_PICSUM_IDS[slot - 1]}/1200/700`;
}

function stableIndex(seed: string, length: number): number {
  let hash = 2166136261;
  for (let index = 0; index < seed.length; index += 1) {
    hash ^= seed.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0) % Math.max(1, length);
}
