import type * as AppTypes from '../shared/app-types';

export interface AssetPopupHost {
  isMobileView(): boolean;
  isAssetPopup(): boolean;
  isTicketAssetPopup(): boolean;
  stackedPopup(): AppTypes.PopupType;
  getPopupTitle(): string;
  ticketHeaderSummary(): string;
  assetFilter(): AppTypes.AssetFilterType;
  assetFilterOptions(): readonly AppTypes.AssetFilterType[];
  assetTypeOptions(): readonly AppTypes.AssetType[];
  assetFilterPanelWidth(): string;
  groupedTicketRows(): AppTypes.ActivityGroup[];
  ticketStickyHeader(): string;
  filteredAssetCards(): AppTypes.AssetCard[];
  showTicketOrderPicker(): boolean;
  ticketDateOrderLabel(): string;
  ticketDateOrderIcon(): string;
  showAssetForm(): boolean;
  assetFormTitle(): string;
  assetForm(): Omit<AppTypes.AssetCard, 'id' | 'requests'>;
  assetFormVisibility(): AppTypes.EventVisibility;
  assetFormRouteStops(): string[];
  pendingAssetDeleteCardId(): string | null;
  pendingAssetDeleteLabel(): string;
  selectedTicketRow(): AppTypes.ActivityListRow | null;
  ticketCodeAvatarUrl(): string;
  ticketCodeInitials(): string;
  ticketCodePersonLine(): string;
  ticketCodeRoleEventLine(): string;
  ticketCodeDateLine(): string;
  ticketQrImageUrl(): string;
  ticketScannerState(): 'idle' | 'reading' | 'success';
  ticketScannerResult(): AppTypes.TicketScanPayload | null;
  ticketScannerResultAvatarUrl(): string;
  ticketScannerResultInitials(): string;
  ticketScannerPersonLine(): string;
  ticketScannerRoleEventLine(): string;
  ticketScannerDateLine(): string;
  assetTypeIcon(type: AppTypes.AssetFilterType): string;
  assetTypeClass(type: AppTypes.AssetFilterType): string;
  shouldShowTicketGroupMarker(groupIndex: number): boolean;
  trackByActivityGroup(index: number, group: AppTypes.ActivityGroup): string;
  trackByActivityRow(index: number, row: AppTypes.ActivityListRow): string;
  activityImageUrl(row: AppTypes.ActivityListRow): string;
  activitySourceLink(row: AppTypes.ActivityListRow): string;
  activitySourceAvatarClass(row: AppTypes.ActivityListRow): string;
  activitySourceAvatarLabel(row: AppTypes.ActivityListRow): string;
  activityLeadingIconCircleClass(row: AppTypes.ActivityListRow): string;
  activityLeadingIcon(row: AppTypes.ActivityListRow): string;
  ticketCardMetaLine(row: AppTypes.ActivityListRow): string;
  canOpenAssetMap(card: AppTypes.AssetCard): boolean;
  isAssetItemActionMenuOpen(card: AppTypes.AssetCard): boolean;
  isAssetItemActionMenuOpenUp(card: AppTypes.AssetCard): boolean;
  eventVisibilityClass(option: AppTypes.EventVisibility): string;
  isEventEditorReadOnly(): boolean;
  closeAssetPopup(): void;
  closeTicketStackedPopup(): void;
  toggleTicketOrderPicker(event?: Event): void;
  selectTicketDateOrder(order: 'upcoming' | 'past', event?: Event): void;
  selectAssetFilter(filter: AppTypes.AssetFilterType): void;
  openMobileAssetFilterSelector(event?: Event): void;
  openAssetForm(card?: AppTypes.AssetCard): void;
  openTicketScannerPopup(event?: Event): void;
  onTicketScroll(event: Event): void;
  openTicketCodePopup(row: AppTypes.ActivityListRow, event?: Event): void;
  openAssetMap(card: AppTypes.AssetCard, event?: Event): void;
  toggleAssetItemActionMenu(card: AppTypes.AssetCard, event: Event): void;
  runAssetItemEditAction(card: AppTypes.AssetCard, event: Event): void;
  runAssetItemDeleteAction(card: AppTypes.AssetCard, event: Event): void;
  closeAssetForm(): void;
  saveAssetCard(): void;
  setAssetFormRouteStop(index: number, value: string): void;
  openAssetFormRouteStopMap(index: number, event?: Event): void;
  refreshAssetFromSourceLink(): void;
  onAssetImageFileSelected(file: File): void;
  cancelAssetDelete(): void;
  confirmAssetDelete(): void;
  retryTicketScanner(event?: Event): void;
  setTicketScrollElement(element: HTMLDivElement | null): void;
  setTicketScannerVideoElement(element: HTMLVideoElement | null): void;
}
