import type * as AppTypes from '../shared/app-types';

export interface AssetPopupHost {
  isMobileView(): boolean;
  isAssetPopup(): boolean;
  isSubEventAssetAssignPopup(): boolean;
  isActivityInviteFriendsPopup(): boolean;
  isTicketAssetPopup(): boolean;
  getPopupTitle(): string;
  assetFilter(): AppTypes.AssetFilterType;
  assetFilterOptions(): readonly AppTypes.AssetFilterType[];
  assetTypeOptions(): readonly AppTypes.AssetType[];
  assetFilterPanelWidth(): string;
  filteredAssetCards(): AppTypes.AssetCard[];
  showAssetForm(): boolean;
  assetFormTitle(): string;
  assetForm(): Omit<AppTypes.AssetCard, 'id' | 'requests'>;
  assetFormVisibility(): AppTypes.EventVisibility;
  assetFormRouteStops(): string[];
  pendingAssetDeleteCardId(): string | null;
  pendingAssetDeleteLabel(): string;
  assetTypeIcon(type: AppTypes.AssetFilterType): string;
  assetTypeClass(type: AppTypes.AssetFilterType): string;
  activityImageUrl(row: AppTypes.ActivityListRow): string;
  activitySourceLink(row: AppTypes.ActivityListRow): string;
  activitySourceAvatarClass(row: AppTypes.ActivityListRow): string;
  activitySourceAvatarLabel(row: AppTypes.ActivityListRow): string;
  activityLeadingIconCircleClass(row: AppTypes.ActivityListRow): string;
  activityLeadingIcon(row: AppTypes.ActivityListRow): string;
  ticketCardMetaLine(row: AppTypes.ActivityListRow): string;
  canOpenAssetMap(card: AppTypes.AssetCard): boolean;
  isAssetItemActionMenuOpen(card: AppTypes.AssetCard): boolean;
  isAssetItemActionMenuOpenUp(card: AppTypes.AssetCard): boolean;
  eventVisibilityClass(option: AppTypes.EventVisibility): string;
  isEventEditorReadOnly(): boolean;
  closeAssetPopup(): void;
  selectAssetFilter(filter: AppTypes.AssetFilterType): void;
  openMobileAssetFilterSelector(event?: Event): void;
  openAssetForm(card?: AppTypes.AssetCard): void;
  openAssetMap(card: AppTypes.AssetCard, event?: Event): void;
  toggleAssetItemActionMenu(card: AppTypes.AssetCard, event: Event): void;
  runAssetItemEditAction(card: AppTypes.AssetCard, event: Event): void;
  runAssetItemDeleteAction(card: AppTypes.AssetCard, event: Event): void;
  closeAssetForm(): void;
  saveAssetCard(): void;
  setAssetFormRouteStop(index: number, value: string): void;
  openAssetFormRouteStopMap(index: number, event?: Event): void;
  refreshAssetFromSourceLink(): void;
  onAssetImageFileSelected(file: File): void;
  cancelAssetDelete(): void;
  confirmAssetDelete(): void;
  subEventAssetAssignHeaderTitle(): string;
  subEventAssetAssignHeaderSubtitle(): string;
  canConfirmSubEventAssetAssignSelection(): boolean;
  closeSubEventAssetAssignPopup(apply?: boolean): void;
  confirmSubEventAssetAssignSelection(event?: Event): void;
  subEventAssetAssignCandidates(): AppTypes.AssetCard[];
  selectedSubEventAssetAssignChips(): AppTypes.AssetCard[];
  toggleSubEventAssetAssignCard(cardId: string, event?: Event): void;
  isSubEventAssetAssignCardSelected(cardId: string): boolean;
  activityInviteSort(): AppTypes.ActivityInviteSort;
  showActivityInviteSortPicker(): boolean;
  toggleActivityInviteSortPicker(event?: Event): void;
  selectActivityInviteSort(sort: AppTypes.ActivityInviteSort): void;
  canConfirmActivityInviteSelection(): boolean;
  confirmActivityInviteSelection(event?: Event): void;
  closeActivityInviteFriends(applyInvitations?: boolean): void;
  selectedActivityInviteChips(): AppTypes.ActivityMemberEntry[];
  activityInviteCandidates(): AppTypes.ActivityMemberEntry[];
  toggleActivityInviteFriend(userId: string, event?: Event): void;
  isActivityInviteFriendSelected(userId: string): boolean;
  activityInviteMetLabel(entry: AppTypes.ActivityMemberEntry): string;
}
